import * as actions from '@controleonline/ui-default/src/store/default/actions';
import * as getters from '@controleonline/ui-default/src/store/default/getters';
import mutations from '@controleonline/ui-default/src/store/default/mutations';
import {
  DEFAULT_EMPLOYEE_CONTEXT,
  formatContextLabel,
  formatDateTimeValue,
  formatDirectionLabel,
  resolvePeopleLabel,
} from '@controleonline/ui-employee/src/shared/employeeFormats';

export default {
  namespaced: true,
  state: {
    item: {},
    items: [],
    resourceEndpoint: 'people_access_events',
    isLoading: false,
    isSaving: false,
    error: '',
    totalItems: 0,
    summary: {},
    filters: {
      context: DEFAULT_EMPLOYEE_CONTEXT,
    },
    reload: false,
    add: false,
    columns: [
      {
        editable: false,
        isIdentity: true,
        sortable: true,
        name: 'id',
        align: 'left',
        label: 'ID',
        format: value => `#${value}`,
      },
      {
        editable: false,
        sortable: true,
        name: 'contextLabel',
        align: 'left',
        label: 'Contexto',
        sortField: 'context',
        format: value => formatContextLabel(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'companyLabel',
        align: 'left',
        label: 'Empresa',
        sortField: 'companyLabel',
        format: (value, column, row) => resolvePeopleLabel(row?.companyLabel || row?.company),
      },
      {
        editable: true,
        sortable: true,
        name: 'peopleLabel',
        align: 'left',
        label: 'Pessoa',
        sortField: 'peopleLabel',
        format: (value, column, row) => resolvePeopleLabel(row?.peopleLabel || row?.people),
      },
      {
        editable: true,
        sortable: true,
        name: 'directionLabel',
        align: 'left',
        label: 'Direcao',
        sortField: 'direction',
        format: value => formatDirectionLabel(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'eventAt',
        align: 'left',
        label: 'Ocorrido em',
        format: value => formatDateTimeValue(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'source',
        align: 'left',
        label: 'Origem',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: true,
        name: 'creationDate',
        align: 'left',
        label: 'Criado em',
        format: value => formatDateTimeValue(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'alterDate',
        align: 'left',
        label: 'Atualizado em',
        format: value => formatDateTimeValue(value),
      },
    ],
  },
  actions,
  getters,
  mutations,
};
