import * as actions from '@controleonline/ui-default/src/store/default/actions';
import * as getters from '@controleonline/ui-default/src/store/default/getters';
import mutations from '@controleonline/ui-default/src/store/default/mutations';
import {
  formatBooleanLabel,
  formatDateValue,
  resolvePeopleLabel,
} from '@controleonline/ui-employee/src/shared/employeeFormats';

export default {
  namespaced: true,
  state: {
    item: {},
    items: [],
    resourceEndpoint: 'employee_profiles',
    isLoading: false,
    isSaving: false,
    error: '',
    totalItems: 0,
    summary: {},
    filters: {},
    reload: false,
    add: false,
    columns: [
      {
        editable: false,
        isIdentity: true,
        sortable: true,
        name: 'id',
        align: 'left',
        label: 'ID',
        format: value => `#${value}`,
      },
      {
        editable: false,
        sortable: true,
        name: 'peopleLabel',
        align: 'left',
        label: 'Funcionario',
        sortField: 'peopleLabel',
        format: (value, column, row) => resolvePeopleLabel(row?.peopleLabel || row?.people),
      },
      {
        editable: false,
        sortable: true,
        name: 'companyLabel',
        align: 'left',
        label: 'Empresa',
        sortField: 'companyLabel',
        format: (value, column, row) => resolvePeopleLabel(row?.companyLabel || row?.company),
      },
      {
        editable: true,
        sortable: true,
        name: 'jobTitle',
        align: 'left',
        label: 'Cargo',
        format: value => value || '-',
      },
      {
        editable: true,
        sortable: true,
        name: 'jobFunction',
        align: 'left',
        label: 'Funcao',
        format: value => value || '-',
      },
      {
        editable: true,
        sortable: true,
        name: 'department',
        align: 'left',
        label: 'Departamento',
        format: value => value || '-',
      },
      {
        editable: true,
        sortable: true,
        name: 'employmentType',
        align: 'left',
        label: 'Vinculo',
        format: value => value || '-',
      },
      {
        editable: true,
        sortable: true,
        name: 'workloadHours',
        align: 'center',
        label: 'Horas',
        format: value => (value !== null && value !== undefined ? String(value) : '-'),
      },
      {
        editable: true,
        sortable: true,
        name: 'active',
        align: 'center',
        label: 'Ativo',
        format: value => formatBooleanLabel(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'admissionDate',
        align: 'left',
        label: 'Admissao',
        format: value => formatDateValue(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'terminationDate',
        align: 'left',
        label: 'Demissao',
        format: value => formatDateValue(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'linkedinHeadline',
        align: 'left',
        label: 'LinkedIn',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: true,
        name: 'creationDate',
        align: 'left',
        label: 'Criado em',
        format: value => formatDateValue(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'alterDate',
        align: 'left',
        label: 'Atualizado em',
        format: value => formatDateValue(value),
      },
    ],
  },
  actions,
  getters,
  mutations,
};
