import * as actions from '@controleonline/ui-default/src/store/default/actions';
import * as getters from '@controleonline/ui-default/src/store/default/getters';
import mutations from '@controleonline/ui-default/src/store/default/mutations';
import {
  DEFAULT_EMPLOYEE_CONTEXT,
  formatAttendanceStatusLabel,
  formatDateValue,
  formatDurationMinutes,
  formatSignedDurationMinutes,
  resolvePeopleLabel,
} from '@controleonline/ui-employee/src/shared/employeeFormats';

export default {
  namespaced: true,
  state: {
    item: {},
    items: [],
    resourceEndpoint: 'report/people/attendance',
    isLoading: false,
    isSaving: false,
    error: '',
    totalItems: 0,
    summary: {},
    filters: {
      context: DEFAULT_EMPLOYEE_CONTEXT,
    },
    reload: false,
    add: false,
    columns: [
      {
        editable: false,
        sortable: true,
        name: 'contextLabel',
        align: 'left',
        label: 'Contexto',
        sortField: 'context',
        format: value => value || '-',
      },
      {
        editable: false,
        externalFilter: true,
        inputType: 'date-range',
        sortable: true,
        name: 'date',
        align: 'left',
        label: 'Periodo do ponto',
        sortField: 'date',
        format: value => formatDateValue(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'department',
        align: 'left',
        label: 'Setor',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: true,
        name: 'peopleLabel',
        align: 'left',
        label: 'Pessoa',
        sortField: 'peopleLabel',
        format: (value, column, row) => resolvePeopleLabel(row?.peopleLabel || value),
      },
      {
        editable: false,
        sortable: true,
        name: 'scheduleLabel',
        align: 'left',
        label: 'Escala',
        sortField: 'scheduleLabel',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: false,
        name: 'entryTimesLabel',
        align: 'left',
        label: 'Entrada(s)',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: false,
        name: 'exitTimesLabel',
        align: 'left',
        label: 'Saida(s)',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: false,
        name: 'workedMinutes',
        align: 'center',
        label: 'Trabalhado',
        format: value => formatDurationMinutes(value),
      },
      {
        editable: false,
        sortable: false,
        name: 'delayMinutes',
        align: 'center',
        label: 'Atraso',
        format: value => formatSignedDurationMinutes(value),
      },
      {
        editable: false,
        sortable: false,
        name: 'overtimeMinutes',
        align: 'center',
        label: 'Hora extra',
        format: value => formatSignedDurationMinutes(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'absenceLabel',
        align: 'left',
        label: 'Falta',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: false,
        name: 'justificationLabel',
        align: 'left',
        label: 'Justificativa',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: true,
        name: 'statusLabel',
        align: 'left',
        label: 'Status',
        sortField: 'status',
        format: value => formatAttendanceStatusLabel(value),
      },
    ],
  },
  actions,
  getters,
  mutations,
};
