import * as actions from '@controleonline/ui-default/src/store/default/actions';
import * as getters from '@controleonline/ui-default/src/store/default/getters';
import mutations from '@controleonline/ui-default/src/store/default/mutations';
import {
  DEFAULT_EMPLOYEE_CONTEXT,
  buildScheduleWindowLabel,
  formatBooleanLabel,
  formatContextLabel,
  formatDateTimeValue,
  formatModeLabel,
  formatTimeValue,
  resolvePeopleLabel,
} from '@controleonline/ui-employee/src/shared/employeeFormats';

export default {
  namespaced: true,
  state: {
    item: {},
    items: [],
    resourceEndpoint: 'people_schedules',
    isLoading: false,
    isSaving: false,
    error: '',
    totalItems: 0,
    summary: {},
    filters: {
      context: DEFAULT_EMPLOYEE_CONTEXT,
    },
    reload: false,
    add: false,
    columns: [
      {
        editable: false,
        isIdentity: true,
        sortable: true,
        name: 'id',
        align: 'left',
        label: 'ID',
        format: value => `#${value}`,
      },
      {
        editable: false,
        sortable: true,
        name: 'contextLabel',
        align: 'left',
        label: 'Contexto',
        sortField: 'context',
        format: value => formatContextLabel(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'companyLabel',
        align: 'left',
        label: 'Empresa',
        sortField: 'companyLabel',
        format: (value, column, row) => resolvePeopleLabel(row?.companyLabel || row?.company),
      },
      {
        editable: true,
        sortable: true,
        name: 'peopleLabel',
        align: 'left',
        label: 'Pessoa',
        sortField: 'peopleLabel',
        format: (value, column, row) => resolvePeopleLabel(row?.peopleLabel || row?.people),
      },
      {
        editable: true,
        sortable: true,
        name: 'professionalPeopleLabel',
        align: 'left',
        label: 'Profissional',
        sortField: 'professionalPeopleLabel',
        format: (value, column, row) =>
          resolvePeopleLabel(row?.professionalPeopleLabel || row?.professionalPeople),
      },
      {
        editable: true,
        sortable: true,
        name: 'modeLabel',
        align: 'left',
        label: 'Modo',
        sortField: 'mode',
        format: value => formatModeLabel(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'label',
        align: 'left',
        label: 'Descricao',
        format: value => value || '-',
      },
      {
        editable: true,
        sortable: true,
        name: 'weekdayLabel',
        align: 'left',
        label: 'Dia',
        sortField: 'weekday',
        format: value => value || '-',
      },
      {
        editable: true,
        sortable: true,
        name: 'windowLabel',
        align: 'left',
        label: 'Janela',
        sortField: 'startTime',
        format: (value, column, row) => buildScheduleWindowLabel(row),
      },
      {
        editable: true,
        sortable: true,
        name: 'periodLabel',
        align: 'left',
        label: 'Periodo',
        sortField: 'startsAt',
        format: value => value || '-',
      },
      {
        editable: true,
        sortable: true,
        name: 'active',
        align: 'center',
        label: 'Ativo',
        format: value => formatBooleanLabel(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'startTime',
        align: 'left',
        label: 'Inicio',
        format: value => formatTimeValue(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'endTime',
        align: 'left',
        label: 'Fim',
        format: value => formatTimeValue(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'startsAt',
        align: 'left',
        label: 'Comeca em',
        format: value => formatDateTimeValue(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'endsAt',
        align: 'left',
        label: 'Termina em',
        format: value => formatDateTimeValue(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'creationDate',
        align: 'left',
        label: 'Criado em',
        format: value => formatDateTimeValue(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'alterDate',
        align: 'left',
        label: 'Atualizado em',
        format: value => formatDateTimeValue(value),
      },
    ],
  },
  actions,
  getters,
  mutations,
};
