import * as actions from '@controleonline/ui-default/src/store/default/actions';
import * as getters from '@controleonline/ui-default/src/store/default/getters';
import mutations from '@controleonline/ui-default/src/store/default/mutations';
import {
  DEFAULT_EMPLOYEE_CONTEXT,
  formatBooleanLabel,
  formatDateValue,
  resolvePeopleLabel,
} from '@controleonline/ui-employee/src/shared/employeeFormats';

export default {
  namespaced: true,
  state: {
    item: {},
    items: [],
    resourceEndpoint: 'people_absences',
    isLoading: false,
    isSaving: false,
    error: '',
    totalItems: 0,
    summary: {},
    filters: {
      context: DEFAULT_EMPLOYEE_CONTEXT,
    },
    reload: false,
    add: false,
    columns: [
      {
        editable: false,
        isIdentity: true,
        sortable: true,
        name: 'id',
        align: 'left',
        label: 'ID',
        format: value => `#${value}`,
      },
      {
        editable: false,
        sortable: true,
        name: 'contextLabel',
        align: 'left',
        label: 'Contexto',
        sortField: 'context',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: true,
        name: 'peopleLabel',
        align: 'left',
        label: 'Pessoa',
        sortField: 'peopleLabel',
        format: (value, column, row) => resolvePeopleLabel(row?.peopleLabel || value),
      },
      {
        editable: false,
        sortable: true,
        name: 'absenceDate',
        align: 'left',
        label: 'Data da falta',
        sortField: 'absenceDate',
        format: value => formatDateValue(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'reason',
        align: 'left',
        label: 'Motivo',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: true,
        name: 'justificationFileLabel',
        align: 'left',
        label: 'Anexo',
        sortField: 'justificationFileLabel',
        format: value => value || '-',
      },
      {
        editable: false,
        sortable: true,
        name: 'statusLabel',
        align: 'left',
        label: 'Status',
        sortField: 'statusLabel',
        format: value => value || '-',
      },
      {
        editable: true,
        sortable: true,
        name: 'active',
        align: 'center',
        label: 'Ativo',
        format: value => formatBooleanLabel(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'creationDate',
        align: 'left',
        label: 'Criado em',
        format: value => formatDateValue(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'alterDate',
        align: 'left',
        label: 'Atualizado em',
        format: value => formatDateValue(value),
      },
    ],
  },
  actions,
  getters,
  mutations,
};
