import * as actions from '@controleonline/ui-default/src/store/default/actions';
import * as getters from '@controleonline/ui-default/src/store/default/getters';
import mutations from '@controleonline/ui-default/src/store/default/mutations';
import * as customActions from './customActions';
import {
  DEFAULT_EMPLOYEE_CONTEXT,
  DEFAULT_EMPLOYEE_EXPORT_KIND,
  formatContextLabel,
  formatDateTimeValue,
  formatExportPeriodLabel,
  formatKindLabel,
  formatStatusLabel,
  resolvePeopleLabel,
} from '@controleonline/ui-employee/src/shared/employeeFormats';

export default {
  namespaced: true,
  state: {
    item: {},
    items: [],
    resourceEndpoint: 'people_export_jobs',
    isLoading: false,
    isSaving: false,
    error: '',
    totalItems: 0,
    summary: {},
    filters: {
      context: DEFAULT_EMPLOYEE_CONTEXT,
      kind: DEFAULT_EMPLOYEE_EXPORT_KIND,
    },
    reload: false,
    add: false,
    columns: [
      {
        editable: false,
        isIdentity: true,
        sortable: true,
        name: 'id',
        align: 'left',
        label: 'ID',
        format: value => `#${value}`,
      },
      {
        editable: false,
        sortable: true,
        name: 'contextLabel',
        align: 'left',
        label: 'Contexto',
        sortField: 'context',
        format: value => formatContextLabel(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'kindLabel',
        align: 'left',
        label: 'Tipo',
        sortField: 'kind',
        format: value => formatKindLabel(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'companyLabel',
        align: 'left',
        label: 'Empresa',
        sortField: 'companyLabel',
        format: (value, column, row) => resolvePeopleLabel(row?.companyLabel || row?.company),
      },
      {
        editable: true,
        sortable: true,
        name: 'peopleLabel',
        align: 'left',
        label: 'Pessoa',
        sortField: 'peopleLabel',
        format: (value, column, row) => resolvePeopleLabel(row?.peopleLabel || row?.people),
      },
      {
        editable: true,
        sortable: true,
        name: 'periodLabel',
        align: 'left',
        label: 'Periodo',
        sortField: 'periodStart',
        format: (value, column, row) => formatExportPeriodLabel(row),
      },
      {
        editable: true,
        sortable: true,
        name: 'statusLabel',
        align: 'left',
        label: 'Status',
        sortField: 'status',
        format: value => formatStatusLabel(value),
      },
      {
        editable: true,
        sortable: true,
        name: 'fileLabel',
        align: 'left',
        label: 'Arquivo',
        sortField: 'fileLabel',
        format: value => value || '-',
      },
      {
        editable: true,
        sortable: true,
        name: 'errorMessage',
        align: 'left',
        label: 'Erro',
        format: value => value || '-',
      },
      {
        editable: true,
        sortable: true,
        name: 'finishedAt',
        align: 'left',
        label: 'Finalizado em',
        format: value => formatDateTimeValue(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'creationDate',
        align: 'left',
        label: 'Criado em',
        format: value => formatDateTimeValue(value),
      },
      {
        editable: false,
        sortable: true,
        name: 'alterDate',
        align: 'left',
        label: 'Atualizado em',
        format: value => formatDateTimeValue(value),
      },
    ],
  },
  actions: {
    ...actions,
    ...customActions,
  },
  getters,
  mutations,
};
